services:
  - type: web
    name: financeai
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn FinanceAI.wsgi:application --bind 0.0.0.0:$PORT"
